config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  get "/cafeteria", to: "cafeteria#index"
  get "/signup", to: "registration#newUser"
  post "/signup", to: "registration#createUser"
  get "/login", to: "login#userlogin"
  get "/logout", to: "session#destroy"
  post "/login", to: "session#create"
  post "/addClerk", to: "registration#add_clerk"
  get "/menu", to: "menu#show"
  post "/menu", to: "menu#create"
  delete "/menu", to: "menu#destroy"
  post "/category", to: "category#create"
  get "/cart", to: "cart#show"
  get "/increase", to: "cart#increase"
  get "/decrease", to: "cart#decrease"
  get "/destroy", to: "cart#destroy"
  get "/addCart", to: "cart#add_to_cart"
  get "/checkout", to: "cart#checkout"
  get "/orderHistory", to: "order#show_history"
  get "/changeStatus", to: "order#change_status"
  get "/moreinfo", to: "order#more_info"
  get "/showCustomers", to: "user#show_customers"
  get "/showClerks", to: "user#show_clerks"
  get "/showUserByMonth", to: "chart#new_user_month"
  get "/chartUsers", to: "user#show_chart_by_month"
  get "/chartSales", to: "order#show_sales_by_month"
  get "/showChartSales", to: "chart#orders_by_month"
  get "/contact", to: "contact#show_contact"
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :order
  belongs_to :orderitem
  belongs_to :user
end

app/controllers/cart_controller.rb
class CartController < ApplicationController

  # show method is responsible for the creating the datastructure of the cart items and for rendenring it in the view
  def show
    cart_obj = Cart.find_by(user_id: session[:user_id])
    if cart_obj
      order_id = cart_obj.order_id
      session[:order_id] = cart_obj.order_id
      @order_items = Orderitem.where(order_id: cart_obj.order_id).order("id")
      session[:count] = countItems
      session[:total] = subTotal
    else
      session[:total] = 0
      session[:count] = 0
    end
  end

  # countItems is responsible for finding total no of items present in Orderitem model
  # for the current logged in user
  def countItems
    order_items_list = Orderitem.where(order_id: session[:order_id])
    count = 0
    if order_items_list
      order_items_list.each do |order_item|
        count = count + order_item.quantity
      end
    end
    return count
  end

  # subtotal is responsible for finding out the total value of all the items present in the cart
  def subTotal
    order_items_list = Orderitem.where(order_id: session[:order_id])
    total = 0
    if order_items_list
      order_items_list.each do |order_item|
        total = total + ((Menuitem.find_by(id: order_item.menuitem_id).price) * order_item.quantity)
      end
    end
    return total
  end

  # decrease method is responsible for reducing the quantity in the cart
  def decrease
    order_item = Orderitem.find_by(id: params[:orderitem_id])
    order_item.quantity -= 1
    order_item.save
    session[:count] = session[:count] - 1
    redirect_to cart_path
  end

  # increase method is responsible for increasing the quantity in the cart
  def increase
    order_item = Orderitem.find_by(id: params[:orderitem_id])
    order_item.quantity += 1
    order_item.save
    session[:count] = session[:count] + 1
    redirect_to cart_path
  end

  # when the quantity will become zero it will destroy the record
  def destroy
    order_item = Orderitem.find_by(id: params[:orderitem_id])
    order_id = order_item
    order_item.destroy()
    count_of_items = Orderitem.where(order_id: order_id).count
    if count_of_items == 0
      Orderitem.destroy_by(id: order_id)
    end
    session[:count] = session[:count] - 1
    redirect_to cart_path
  end

  def add_to_cart
    # we will check if the orderitem already exists for the current user
    cart = Cart.find_by(user_id: session[:user_id])
    if cart
      # if the user have something in the cart already we will just add
      # the item into the already existing order
      order_id = cart.order_id
      order_item = Orderitem.find_by(order_id: order_id, menuitem_id: params[:menuitem_id])
      if order_id == nil
        order_id = Order.create(user_id: session[:user_id], status: "pending")
        session[:order_id] = order_id
        session[:total] = Menuitem.find_by(id: order_item.menuitem_id).price
        session[:count] = 1
        order_id.save
      end
      if order_item
        order_item.quantity += 1
        order_item.save
        session[:count] = session[:count] + 1
      else
        # we will create an orderitem
        order_item = Orderitem.create(order_id: order_id, menuitem_id: params[:menuitem_id], quantity: 1)
        order_item.save
        session[:count] = session[:count] + 1
      end
    else
      order = Order.create(user_id: session[:user_id], status: "pending")
      order.save
      session[:order_id] = order.id
      order_item = Orderitem.create(order_id: order.id, menuitem_id: params[:menuitem_id], quantity: 1)
      order_item.save
      session[:count] = 1
      cart = Cart.create(order_id: order.id, orderitem_id: order_item.id, user_id: session[:user_id])
      cart.save
    end
    redirect_to menu_path
  end

  # checkout method is reponsible for clearing all the data from the cart model/ db and change
  # the status of the order as confirmed
  def checkout
    order_id = Cart.find_by(user_id: session[:user_id]).order_id
    order = Order.find_by(id: order_id)
    order.status = "confirmed"
    order.save
    Cart.destroy_by(user_id: session[:user_id])
    session[:total] = 0
    session[:count] = 0
    redirect_to orderHistory_path
  end
end

app/views/cart/show.html.erb
<div class="row justify-content-center">
<h1>Cart</h1>
<% if session[:view]==2%>
<%= render partial: "menu/categoryform"%>
<%= render partial: "menu/menuform"%>
<%end%>
</div>
<div>
<% if flash[:notice]%>
<p> <%= flash[:notice] %></p>
<% end%>

<% if @order_items%>
<h6>Subtotal items (<span><%= session[:count]%></span> ): <span class="text-danger"><%= session[:total]%></span></h6>

<table class = "table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <% if session[:view]==2%>
      <th>Delete</th>
      <% end %>
      <th> Quantity</th>
      <th>Total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @order_items.each do |order_item| %>
    <% menu_item = Menuitem.find_by(id:order_item.menuitem_id)%>
      <tr>
        <td><%= menu_item.name %></td>
        <td><%= menu_item.description %></td>
        <td><%= menu_item.price %></td>
        <% if session[:view]==2%>
        <td><%= link_to 'Destroy', menu_path(id: menu_item.id, name: menu_item.name), method: :delete, data: { confirm: 'Are you sure?' } %></</td>
        <%end %>
        <td>
        <% if order_item.quantity == 0%>
        <%= link_to "Del", destroy_path(orderitem_id: order_item.id), class:"btn btn-secoundary" %>
        <% else %>
        <%= link_to "+", increase_path(orderitem_id: order_item.id), class:"btn btn-secoundary" %>
        <% end %>
        <%= order_item.quantity%>
        <%= link_to "-", decrease_path(orderitem_id: order_item.id), class:"btn btn-secoundary" %>
        </td>
        <td><%= menu_item.price * order_item.quantity%> </td>
      </tr>
    <% end %>
  </tbody>
</table>

</div>
<div class="row justify-content-center">
<%= link_to 'Checkout',checkout_path,method: :get,class: "btn btn-danger"%>
</div>
<%else%>
<div class="row justify-content-center ">
<p> <strong> No items to display</strong> </p>
</div>
<%end%>