config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  get "/cafeteria", to: "cafeteria#index"
  get "/signup", to: "registration#newUser"
  post "/signup", to: "registration#createUser"
  get "/login", to: "login#userlogin"
  get "/logout", to: "session#destroy"
  post "/login", to: "session#create"
  post "/addClerk", to: "registration#add_clerk"
  get "/menu", to: "menu#show"
  post "/menu", to: "menu#create"
  delete "/menu", to: "menu#destroy"
  post "/category", to: "category#create"
  get "/cart", to: "cart#show"
  get "/increase", to: "cart#increase"
  get "/decrease", to: "cart#decrease"
  get "/destroy", to: "cart#destroy"
  get "/addCart", to: "cart#add_to_cart"
  get "/checkout", to: "cart#checkout"
  get "/orderHistory", to: "order#show_history"
  get "/changeStatus", to: "order#change_status"
  get "/moreinfo", to: "order#more_info"
  get "/showCustomers", to: "user#show_customers"
  get "/showClerks", to: "user#show_clerks"
  get "/showUserByMonth", to: "chart#new_user_month"
  get "/chartUsers", to: "user#show_chart_by_month"
  get "/chartSales", to: "order#show_sales_by_month"
  get "/showChartSales", to: "chart#orders_by_month"
  get "/contact", to: "contact#show_contact"
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  def show
    @menu_items = Menuitem.where(status: "active")
  end

  def create
    menu_item = Menuitem.find_by(name: params[:name])
    if menu_item
      if menu_item.status == "active"
        flash[:notice] = "Item #{params[:name]} already exists"
      end
      menu_item.status = "active"
      menu_item.save
      @menu_items = Menuitem.where(status: "active")

      render :show
    else
      @menu_item = Menuitem.create(name: params[:name], category_id: params[:category_id], description: params[:description], price: params[:price], status: "active")
      if @menu_item.save
        flash[:success] = "Item #{params[:name]} successfully created"
        render :show
      else
        render :show
      end
    end
  end

  def destroy
    menu_item = Menuitem.find_by(id: params[:id])
    menu_item.status = "deactive"
    menu_item.save
    flash[:notice] = "Item #{params[:name]} is deleted"
    redirect_to menu_path
  end
end

app/views/menu/_categoryform.html.erb
<button type="button" class="btn btn-secondary" data-toggle="modal" data-target ="#categoryItemModal" >Add Category </button>
  <div class="modal fade" id="categoryItemModal" >
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title">Add Category</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>

        </div>
        <div class="modal-body">
          <div class="row justify-content-center">
            <div class="align-items-center">
              <%= form_with url: category_path do |form|%>

              <div class="mb-3 form-group">
                <%= form.label :name%>
                <%= form.text_field :name, class: "form-control", placeholder: "Dosa"%>
              </div>

              <div class="mb-3">
                <%= form.submit "Create Item", class:"btn btn-primary"%>
              </div>
          <% end%>
        </div>
        </div>

        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>

    </div>
  </div>

app/views/menu/_menuform.html.erb
<button type="button" class="btn btn-secondary" data-toggle="modal" data-target ="#menuItemModal" >Add Menu Item </button>
  <div class="modal fade" id="menuItemModal" >
    <div class="modal-dialog">


      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title">Add Menu Item</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>

        </div>
        <div class="modal-body">
          <div class="row justify-content-center">
            <div class="align-items-center">
              <%= form_with url: menu_path do |form|%>


                <div class="mb-3 form-group">
                <%= form.label :Category%>
                 <%= form.select(:category_id ,options_from_collection_for_select(Category.all,'id','name')) %>
                </div>

              <div class="mb-3 form-group">
                <%= form.label :name%>
                <%= form.text_field :name, class: "form-control", placeholder: "Dosa"%>
              </div>

              <div class="mb-3 form-group">
                <%= form.label :description %>
                <%= form.text_area :description, class: "form-control", placeholder: "description of the dish"%>
              </div>

              <div class="mb-3 form-group">
                <%= form.label :price %>
                <%= form.text_field :price, class: "form-control", placeholder: "100.0 or 100"%>
              </div>


              <div class="mb-3">
                <%= form.submit "Create Item", class:"btn btn-primary"%>
              </div>
          <% end%>
        </div>
        </div>

        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>

    </div>
  </div>

app/views/menu/show.html.erb
<div>
<h1>Menu Items</h1>
<% if session[:view]==2%>
<%= render partial: "menu/categoryform"%>
<%= render partial: "menu/menuform"%>
<%end%>
</div>
<div>
<% if flash[:notice]%>
<p> <%= flash[:notice] %></p>
<% end%>

<table class = "table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Category</th>
      <%if session[:view]==1 or session[:view]==3%>
      <th> Add to Cart</th>
      <%end%>
      <% if session[:view]==2%>
      <th>Delete</th>
      <% end %>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  <% if @menu_items==nil%>
  <% @menu_items = Menuitem.all%>
  <%end%>
    <% @menu_items.each do |menu_item| %>
      <tr>
        <td><%= menu_item.name %></td>
        <td><%= menu_item.description %></td>
        <td><%= menu_item.price %></td>
        <td><%= Category.find_by(id:menu_item.category_id).name %></td>
        <% if session[:view]==2%>
        <td><%= link_to 'Destroy', menu_path(id: menu_item.id, name: menu_item.name), method: :delete, data: { confirm: 'Are you sure?' } %></</td>
        <%end %>
        <% if session[:view]==1 or session[:view]==3%>
        <td>
        <%= link_to 'Add to Cart', addCart_path(menuitem_id: menu_item.id),method: :get,class: "btn btn-secondary"%>
        </td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>
</div>