config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  get "/cafeteria", to: "cafeteria#index"
  get "/signup", to: "registration#newUser"
  post "/signup", to: "registration#createUser"
  get "/login", to: "login#userlogin"
  get "/logout", to: "session#destroy"
  post "/login", to: "session#create"
  post "/addClerk", to: "registration#add_clerk"
  get "/menu", to: "menu#show"
  post "/menu", to: "menu#create"
  delete "/menu", to: "menu#destroy"
  post "/category", to: "category#create"
  get "/cart", to: "cart#show"
  get "/increase", to: "cart#increase"
  get "/decrease", to: "cart#decrease"
  get "/destroy", to: "cart#destroy"
  get "/addCart", to: "cart#add_to_cart"
  get "/checkout", to: "cart#checkout"
  get "/orderHistory", to: "order#show_history"
  get "/changeStatus", to: "order#change_status"
  get "/moreinfo", to: "order#more_info"
  get "/showCustomers", to: "user#show_customers"
  get "/showClerks", to: "user#show_clerks"
  get "/showUserByMonth", to: "chart#new_user_month"
  get "/chartUsers", to: "user#show_chart_by_month"
  get "/chartSales", to: "order#show_sales_by_month"
  get "/showChartSales", to: "chart#orders_by_month"
  get "/contact", to: "contact#show_contact"
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items
  has_many :cart
end

app/controllers/order_controller.rb
class OrderController < ApplicationController
  def show_history
    # we will shoe_histroy only if the user exits
    # therefore, we will check the log-in criteria using a if condition
    # if user is not logged in then we will redirect the guest user to cafteria_path
    if session[:user_id]
      # check if the user is admin to do so and avoid quering role of user over and over again in db
      # i have set the variable view in the session object in which if it's value is 2 then we will show the
      # the admin view
      if session[:view] == 2
        orders = Order.where("status = ? OR status = ? ", "confirmed", "delivered").order("id")
        @order_items_list = []
        orders.each do |order|
          order_hash = Hash.new()
          order_hash[:order_id] = order.id
          order_hash[:total] = 0
          order_hash[:count] = 0
          order_hash[:status] = order.status
          order_hash[:created_at] = order.created_at.to_date
          orderitem = Orderitem.where(order_id: order.id)
          orderitem.each do |item|
            order_hash[:total] += ((Menuitem.find_by(id: item.menuitem_id).price) * item.quantity)
            order_hash[:count] += (item.quantity)
          end
          @order_items_list.push(order_hash)
        end
      else
        # if the control reaches here then it means, the user is either a customer or clerk
        orders = Order.where(user_id: session[:user_id]).order("id")
        @order_items_list = []
        orders.each do |order|
          order_hash = Hash.new()
          order_hash[:order_id] = order.id
          order_hash[:total] = 0
          order_hash[:count] = 0
          order_hash[:status] = order.status
          order_hash[:created_at] = order.created_at.to_date
          orderitem = Orderitem.where(order_id: order.id)
          orderitem.each do |item|
            order_hash[:total] += ((Menuitem.find_by(id: item.menuitem_id).price) * item.quantity)
            order_hash[:count] += (item.quantity)
          end
          @order_items_list.push(order_hash)
        end
      end
    else
      # the control will reach here if the session[:user_id ] doesn't exists or it's value is nil
      # that means the user is not logged in
      redirect_to cafteria_path
    end
  end

  def change_status
    if session[:view] == 2
      order_id = params[:order_id]
      order = Order.find_by(id: order_id)
      order.status = params[:status]
      order.save
      redirect_to orderHistory_path
    else
      # the control will reach here if the session[:user_id ] doesn't exists or it's value is nil
      # that means the user is not logged in
      redirect_to cafteria_path
    end
  end

  def more_info
    #more_info will render the entire information about a particular order
    order = Order.find_by(id: params[:order_id])
    @order_items_list = []
    @subTotal = 0
    @totalItems = 0
    @orderId = order.id
    @created_at = order.created_at.to_date
    @status = order.status.capitalize()
    order_items = Orderitem.where(order_id: order.id)
    order_items.each do |item|
      order_hash = Hash.new()
      order_hash[:item_id] = item.id
      menu_item = Menuitem.find_by(id: item.menuitem_id)
      order_hash[:total] = (menu_item.price * item.quantity)
      order_hash[:count] = (item.quantity)
      @subTotal += order_hash[:total]
      @totalItems += order_hash[:count]
      order_hash[:name] = menu_item.name.capitalize()
      @order_items_list.push(order_hash)
    end
  end

  def show_sales_by_month
    if session[:view] != 2
      redirect_to cafeteria_path
    end
  end
end

app/views/order/more_info.html.erb
<div>
<h1>Order History</h1>
<h4>SubTotal(<%=@totalItems%> ): <span class= "text-danger"> <%= @subTotal%></span> </h4>
<h5>Order Id: <%= @orderId%></h5>
<h5> Status : <%= @status%> </h5>
<h5>Date Ordered: <span><%= @created_at%></span> </h5>
</div>
<div>
<% if flash[:notice]%>
<p> <%= flash[:notice] %></p>
<% end%>
<table class = "table table-hover">
  <thead>
    <tr>
      <th>Item ID</th>
      <th>Item Name </th>
      <th>Quantity</th>
      <th>Total Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @order_items_list.each do |order| %>
      <tr>
        <td><%= order[:item_id] %></td>
        <td><%= order[:name] %></td>
        <td><%= order[:count] %></td>
        <td><%= order[:total]%> </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<div class="row justify-content-center">
  <%= link_to "Back" ,:back,class:"btn btn-outline-primary btn-lg"%>
</div>

app/views/order/show_history.html.erb
<div>
<h1>Order History</h1>
</div>
<div>
<% if flash[:notice]%>
<p> <%= flash[:notice] %></p>
<% end%>

<table class = "table table-hover">
  <thead>
    <tr>
      <th>Order ID</th>
      <th>Total Items</th>
      <th>Total Price</th>
      <th>Date of Order</th>
      <th> Status</th>
      <% if session[:view]==2%>
      <th>Change Status</th>
      <% end %>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @order_items_list.each do |order| %>
      <tr>
        <td><%= order[:order_id] %></td>
        <td><%= order[:count] %></td>
        <td><%= order[:total] %></td>
        <td> <%= order[:created_at]%></td>
        <td> <%= order[:status]%> </td>
        <% if session[:view]==2%>
        <td><%= link_to 'Change Status',changeStatus_path(order_id: order[:order_id],status: "delivered"),method: :get,class: "btn btn-primary"%> </td>
        <td><%= link_to 'More info',moreinfo_path(order_id: order[:order_id]),method: :get,class: "btn btn-secondary"%></td>
        <%end %>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/order/show_sales_by_month.html.erb
<div vlass="mb-3">
<h4>Sales By Month</h4>
</div>
<div class="mb-3">
<%= column_chart showChartSales_path %>
</div>