config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  get "/cafeteria", to: "cafeteria#index"
  get "/signup", to: "registration#newUser"
  post "/signup", to: "registration#createUser"
  get "/login", to: "login#userlogin"
  get "/logout", to: "session#destroy"
  post "/login", to: "session#create"
  post "/addClerk", to: "registration#add_clerk"
  get "/menu", to: "menu#show"
  post "/menu", to: "menu#create"
  delete "/menu", to: "menu#destroy"
  post "/category", to: "category#create"
  get "/cart", to: "cart#show"
  get "/increase", to: "cart#increase"
  get "/decrease", to: "cart#decrease"
  get "/destroy", to: "cart#destroy"
  get "/addCart", to: "cart#add_to_cart"
  get "/checkout", to: "cart#checkout"
  get "/orderHistory", to: "order#show_history"
  get "/changeStatus", to: "order#change_status"
  get "/moreinfo", to: "order#more_info"
  get "/showCustomers", to: "user#show_customers"
  get "/showClerks", to: "user#show_clerks"
  get "/showUserByMonth", to: "chart#new_user_month"
  get "/chartUsers", to: "user#show_chart_by_month"
  get "/chartSales", to: "order#show_sales_by_month"
  get "/showChartSales", to: "chart#orders_by_month"
  get "/contact", to: "contact#show_contact"
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def userlogin
    if session[:user_id]
      # if the user is already logged in then we will redirect that user to home page
      # ehich in our case is cafeteria page
      redirect_to cafeteria_path
    end
  end
end

app/views/login/userlogin.html.erb
<div class="row justify-content-center">
<div class="align-items-center col-4 mb-3">
<h1 class="text-center">Welcome Back!</h1>
<%= form_with  url: login_path do |form|%>
<div class="mb-3 form-group">
<%= form.label :username%>
<%= form.text_field :name, class: "form-control", placeholder: "example@gmail.com"%>
</div>
<div class="mb-3">
<%= form.label :password%>
<%= form.password_field :password, class: "form-control", placeholder: "password"%>
</div>
<div class="mb-3">
<%= form.label :password_confirmation%>
<%= form.password_field :password_confirmation, class: "form-control",placeholder: "re-type password"%>
</div>
<div class="mb-3">
<%= form.submit "Log In", class:"btn btn-primary"%>
</div>
<% end%>
</div>
</div>